### ISSUE TITLE
Website design: change the main image in the header

### ISSUE THREAD

**Issue by rskikuli** [Collective68/task-management#16]
The image that is at the moment at the header is black and does not reflect a positive vibe. Let's keep the animation, but use another image or a more 'optimistic' color. 
Deadline: 22.03.2018.

**Comment by rskikuli** [comment]
@silvaarapi @sidorelauku the deadline is close. Please check.

**Comment by nafieshehu** [comment]
@sidorelauku @silvaarapi should we close the issue since the image is changed now?

**Comment by silvaarapi** [comment]
Yes, closing this one.
