### ISSUE TITLE
C68 website reponsive on mobile browsers

### ISSUE THREAD

**Issue by rskikuli** [Collective68/task-management#17]
The mobile version of the website needs to be more responsive. At this moment the images seem stretched.

**Comment by silvaarapi** [comment]
The website is responsive on mobile actually. The issue appears because of the changes we made to make the images appear in full size. @sidorelauku since you worked on this, do you think we can adjust them for mobile too? if not, let's turn it back as it was and I can work on editing the images.

**Comment by rskikuli** [comment]
@sidorelauku this is high priority in my opinion. Thanks

**Comment by sidorelauku** [comment]
Worked on this last week with texts to be mobile responsive. Will work on the images until 12.04.2018.

**Comment by blackpenguins** [comment]
@sidorelauku I think this is done right?

**Comment by rskikuli** [comment]
Tested this and seems ok. Closing this. Thanks for the amazing work @sidorelauku !
