### ISSUE TITLE
Domain redirection issue for our website

### ISSUE THREAD

**Issue by rskikuli** [Collective68/task-management#20]
The issue with the domain hasn't been solved yet. We need to fix this asap since the website is needed for various applications for partnerships we are doing at this time. Deadline: week 12.03.2018.

**Comment by rskikuli** [comment]
@nafieshehu please test and confirm that this is working. Deadline: 24.03.2018.

**Comment by nafieshehu** [comment]
I tested it yesterday when Sidorela made some changes and I weren't able to acces the website. Also today after I committed something on github was redirecting again. Now is working in all my devices and browsers but still is the issue after we commit sth on github.

**Comment by rskikuli** [comment]
Seems to work fine at the moment. Closing this issue.
