### ISSUE TITLE
Po Flet Valbona Website

### ISSUE THREAD

**Issue by nafieshehu** [Collective68/task-management#29]
We should finish Po Flet Valbona webiste until 30.04.2018.

**Comment by sidorelauku** [comment]
Theme proposal

Link 1: https://janczizikow.github.io/sleek/

Link 2: https://sylhare.github.io/Type-on-Strap/

with @nafieshehu  we will have a look at the codes and update here for the final proposal.

**Comment by rskikuli** [comment]
Website is online. Closing this.
