### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by nafieshehu** [Collective68/task-management#9]
We need to change the fonts for the website.

**Comment by sidorelauku** [comment]
What font will be used?

**Comment by rskikuli** [comment]
Let's work with this one for the logo and main titles https://fonts.google.com/specimen/Secular+One and this one for the normal text https://fonts.google.com/specimen/Open+Sans.

**Comment by rskikuli** [comment]
@sidorelauku deadline for this: 26.03.2018.

**Comment by silvaarapi** [comment]
@sidorelauku changed the fonts since 26.03.2018. The fonts we are using are Open Sans and Secular One. Closing this issue.
